### ISSUE TITLE
测试指标比论文高

### ISSUE THREAD

**Issue by hhhhhhx16** [justchenhao/BIT_CD#11]
你好，我用了你们提供的best_ckpt.pt文件，在LEVIR数据集上的F1是0.94，比论文高了很多，请问是后续进行了优化么？

**Comment by guanyuezhen** [comment]
![`OJR{%{{J1D%R6VWLM T7@2](https://user-images.githubusercontent.com/31332365/143285157-d23472c7-d90e-4e35-9eea-5456e7e5c162.png)

**Comment by xbysq** [comment]
> ![`OJR{%{{J1D%R6VWLM T7@2](https://user-images.githubusercontent.com/31332365/143285157-d23472c7-d90e-4e35-9eea-5456e7e5c162.png)

请问你是如何训练的？

**Comment by lm-ZHAO98** [comment]
> 你好，我用了你们提供的best_ckpt.pt文件，在LEVIR数据集上的F1是0.94，比论文高了很多，请问是后续进行了优化么？
你好，我复现这个模型遇到一些问题，能向你请教一下吗？

**Comment by lm-ZHAO98** [comment]
> 你好，我用了你们提供的best_ckpt.pt文件，在LEVIR数据集上的F1是0.94，比论文高了很多，请问是后续进行了优化么？

你好，我复现这个模型遇到一些问题，能请教一下你吗？
