### ISSUE TITLE
Lower index

### ISSUE THREAD

**Issue by xbysq** [justchenhao/BIT_CD#14]
I conducted my experiments on the NVIDIA-SMI 410.72 GPU server. The parameters are consistent with what you gave. My results are as follows: acc: 0.97853 miou: 0.78005 mf1: 0.86238 iou_0: 0.97787 iou_1: 0.58222 F1_0: 0.98881 F1_1: 0.73596 precision_0: 0.98745 precision_1: 0.76064 recall_0: 0.99017 recall_1: 0.71283.

**Comment by yuwanting828** [comment]
Hello, have you come back? Or did you find a problem with the result gap? Can I leave a QQ or other contact to communicate?

**Comment by xbysq** [comment]
> Hello, have you come back? Or did you find a problem with the result gap? Can I leave a QQ or other contact to communicate?

I am not sure if I have solved it, but the index has definitely improved. We can communicate with each other.
