### ISSUE TITLE
Training Error

### ISSUE THREAD

**Issue by tessell-aditya** [justchenhao/BIT_CD#35]
Hello, We are trying to execute your training model code, and it is failing with different errors, when using NAIP imagery dataset as train data. But it works normal when using LEVID-CD dataset. 

We are feeding in the data with 256 chip size with same folder structure as suggested (A, B, label, list). Do we need to consider anything and change the training data?

Tried to fix the errors but fixing one leads to other errors as shown below. Any help on this would be highly appreciated. 
Thanks in advance.

![image](https://user-images.githubusercontent.com/125379684/218774878-af45351b-1d8b-4813-861a-15a3528c32f3.png)
![image](https://user-images.githubusercontent.com/125379684/218774673-b4208b35-5118-49dc-8cd3-32179de4e652.png)
![image](https://user-images.githubusercontent.com/125379684/218774409-b927fadf-5b41-4467-bac8-a629598ff5ee.png)

**Comment by WesternTrail** [comment]
I have the same problem as you!Have you solved it?

**Comment by tessell-aditya** [comment]
Yes, I seem to have found the fix. When creating the label tiles, they are exported as RGB, make sure to get them as gray scale and changing the bit depth of the label to 8 bit unsigned did the trick for me.

**Comment by WesternTrail** [comment]
thank you!
