### ISSUE TITLE
Some problems about the image size of training process

### ISSUE THREAD

**Issue by WesternTrail** [justchenhao/BIT_CD#36]
In the original paper, it was mentioned that the original image of 1024x1024 resolution was cut into 256x256 patches during training, but I think the source code implementation is to directly resize the 1024x1024 image to 256x256? Why do you do this instead of following the original?

![image](https://user-images.githubusercontent.com/28615285/221486853-e90645ec-b1a9-448f-86b9-4a5596f65648.png)
![image](https://user-images.githubusercontent.com/28615285/221486911-62691225-0635-49fa-9114-7e6e0016a41b.png)

**Comment by docShen** [comment]
我也发现了，这里并没有和原文一样
