### ISSUE TITLE
Something for 'stride' of the Resnet18 in Backbone

### ISSUE THREAD

**Issue by Tom-Dongfang** [justchenhao/BIT_CD#48]
Hello, I have recently read your code and am very interested in your work. However, I also have a few questions that I would like to answer:

1) In the paper, stride of the last two stages of resnet18 were replaced with 1, but the corresponding settings were not found in the code. In line 137 of models/resnet.py, 'self. structures=[2, 2, 2, 2, 2]'.  If we follow the settings in the paper, should we change it as 'self. structures=[2, 2, 1, 1]' ?
![1](https://github.com/justchenhao/BIT_CD/assets/44158474/782e2f1b-d317-4bb5-a5d2-8bc9f29a1360)

2) May I ask if the setting in line 100 of model/trainer.py indicates that it is possible to read a model and continue training?
![2](https://github.com/justchenhao/BIT_CD/assets/44158474/51f38a0e-b87c-4d4d-abfc-8ef57634e5d1)

**Comment by justchenhao** [comment]
Thanks for your attention. You can see that we init the reset backbone with replace_stride_with_dilation=[False,True,True] (see line 160 in `networks.py`). The stage with dilation has a stride of 1. (see line 196 in `resnet.py`)
