### ISSUE TITLE
About the eval results

### ISSUE THREAD

**Issue by Richardych** [justchenhao/BIT_CD#9]
hi,

thanks for the great work. 

When I test the checkpoint of this repo, I only get:
`acc: 0.94999 miou: 0.48876 mf1: 0.51403 iou_0: 0.94992 iou_1: 0.02761 F1_0: 0.97431 F1_1: 0.05374 precision_0: 0.95038 precision_1: 0.74621 recall_0: 0.99949 recall_1: 0.02788`

the mean F1 score is two poor compared to you paper claimed, why?

**Comment by Youskrpig** [comment]
> hi,
> 
> thanks for the great work.
> 
> When I test the checkpoint of this repo, I only get: `acc: 0.94999 miou: 0.48876 mf1: 0.51403 iou_0: 0.94992 iou_1: 0.02761 F1_0: 0.97431 F1_1: 0.05374 precision_0: 0.95038 precision_1: 0.74621 recall_0: 0.99949 recall_1: 0.02788`
> 
> the mean F1 score is two poor compared to you paper claimed, why?

I solved it by modify the img_size to 1024 when running evaluation.
